name: "Snyk"

on:
  push:
    branches: [main]
  # Run the job at the end of every day
  schedule:
    - cron: "0 0 * * *"

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  DEFAULT_JDK_VERSION: 11

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "${{ env.DEFAULT_JDK_VERSION }}"

      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-2-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Build Keycloak
        run: mvn clean install  -nsu -B -e -Dmaven.test.skip -DskipQuarkus -DskipTestsuite -DskipExamples -DskipTests

      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for Java vulnerabilities
        run: snyk test --org=boliveir --all-projects --exclude=testsuite,adapters,examples,wildfly,misc,integration,distribution --sarif-file-output=snyk.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: "${{ env.SNYK_TOKEN }}"
      # Comment
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
